"""AQD-004: Post-LLM SQL Injection Analyzer.

Performs AST-level analysis of SQL generated by the LLM to detect
injection artifacts that survived prompt-level scanning.

Detection Rules
---------------
- UNION injection           -- UNION [ALL] SELECT appended
- Tautology clauses         -- 1=1, 'a'='a', OR TRUE
- Stacked queries           -- multiple statements via semicolons
- Comment bypasses          -- inline (/**/) and line (--) comments
- Dynamic SQL               -- EXEC, sp_executesql, EXECUTE IMMEDIATE
- System table access       -- information_schema, sys.*, pg_catalog
- File operations           -- INTO OUTFILE, LOAD_FILE, COPY
- Privilege escalation      -- GRANT, REVOKE, CREATE USER
- Time-based blind          -- SLEEP, BENCHMARK, WAITFOR DELAY
- Dangerous DDL             -- DROP, ALTER, TRUNCATE
"""

from __future__ import annotations

import re

import structlog

from queryvault.app.models.threat import InjectionAnalysisResult

logger = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Rule definitions: (rule_name, pattern, threat_label, score_contribution)
# ---------------------------------------------------------------------------

_RULES: list[tuple[str, re.Pattern[str], str, float]] = [
    # UNION injection
    ("union_injection", re.compile(
        r"\bUNION\s+(ALL\s+)?SELECT\b", re.IGNORECASE,
    ), "UNION SELECT injection", 0.9),

    # Tautologies
    ("tautology_1eq1", re.compile(
        r"\b1\s*=\s*1\b", re.IGNORECASE,
    ), "Tautology (1=1)", 0.8),
    ("tautology_str", re.compile(
        r"'[^']*'\s*=\s*'[^']*'", re.IGNORECASE,
    ), "Tautology (string equality)", 0.8),
    ("tautology_or_true", re.compile(
        r"\bOR\s+(TRUE|1)\b", re.IGNORECASE,
    ), "Tautology (OR TRUE)", 0.8),

    # Stacked queries
    ("stacked_queries", re.compile(
        r";\s*(SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|GRANT|REVOKE|TRUNCATE)\b",
        re.IGNORECASE,
    ), "Stacked query detected", 0.9),

    # Comment bypasses
    ("inline_comment", re.compile(
        r"/\*.*?\*/", re.IGNORECASE | re.DOTALL,
    ), "Inline comment bypass", 0.5),
    ("line_comment", re.compile(
        r"--\s*\S", re.IGNORECASE,
    ), "Line comment bypass", 0.4),

    # Dynamic SQL
    ("exec_call", re.compile(
        r"\bEXEC(\s+|\()", re.IGNORECASE,
    ), "EXEC call detected", 0.9),
    ("sp_executesql", re.compile(
        r"\bsp_executesql\b", re.IGNORECASE,
    ), "sp_executesql detected", 0.9),
    ("execute_immediate", re.compile(
        r"\bEXECUTE\s+IMMEDIATE\b", re.IGNORECASE,
    ), "EXECUTE IMMEDIATE detected", 0.9),

    # System tables
    ("information_schema", re.compile(
        r"\binformation_schema\b", re.IGNORECASE,
    ), "information_schema access", 0.7),
    ("sys_tables", re.compile(
        r"\bsys\.(tables|columns|objects|databases|schemas)\b", re.IGNORECASE,
    ), "System table access (sys.*)", 0.7),
    ("pg_catalog", re.compile(
        r"\bpg_catalog\b", re.IGNORECASE,
    ), "pg_catalog access", 0.7),
    ("sqlite_master", re.compile(
        r"\bsqlite_master\b", re.IGNORECASE,
    ), "sqlite_master access", 0.7),

    # File operations
    ("into_outfile", re.compile(
        r"\bINTO\s+(OUTFILE|DUMPFILE)\b", re.IGNORECASE,
    ), "INTO OUTFILE/DUMPFILE", 1.0),
    ("load_file", re.compile(
        r"\bLOAD_FILE\s*\(", re.IGNORECASE,
    ), "LOAD_FILE() call", 1.0),
    ("copy_from_to", re.compile(
        r"\bCOPY\s+\w+\s+(FROM|TO)\b", re.IGNORECASE,
    ), "COPY FROM/TO detected", 0.9),

    # Privilege escalation
    ("grant_stmt", re.compile(
        r"\bGRANT\s+(ALL|SELECT|INSERT|UPDATE|DELETE|EXECUTE|CREATE|ALTER)\b",
        re.IGNORECASE,
    ), "GRANT statement", 1.0),
    ("revoke_stmt", re.compile(
        r"\bREVOKE\s+(ALL|SELECT|INSERT|UPDATE|DELETE|EXECUTE|CREATE|ALTER)\b",
        re.IGNORECASE,
    ), "REVOKE statement", 1.0),
    ("create_user", re.compile(
        r"\bCREATE\s+(USER|LOGIN|ROLE)\b", re.IGNORECASE,
    ), "CREATE USER/ROLE", 1.0),

    # Time-based blind injection
    ("sleep_call", re.compile(
        r"\bSLEEP\s*\(\d+\)", re.IGNORECASE,
    ), "SLEEP() call (time-based blind)", 0.9),
    ("benchmark_call", re.compile(
        r"\bBENCHMARK\s*\(", re.IGNORECASE,
    ), "BENCHMARK() call", 0.9),
    ("waitfor_delay", re.compile(
        r"\bWAITFOR\s+DELAY\b", re.IGNORECASE,
    ), "WAITFOR DELAY (time-based blind)", 0.9),

    # Dangerous DDL
    ("drop_stmt", re.compile(
        r"\bDROP\s+(TABLE|DATABASE|INDEX|VIEW|SCHEMA|PROCEDURE|FUNCTION)\b",
        re.IGNORECASE,
    ), "DROP statement", 1.0),
    ("alter_stmt", re.compile(
        r"\bALTER\s+(TABLE|DATABASE|USER|ROLE)\b", re.IGNORECASE,
    ), "ALTER statement", 0.8),
    ("truncate_stmt", re.compile(
        r"\bTRUNCATE\s+TABLE\b", re.IGNORECASE,
    ), "TRUNCATE TABLE", 1.0),

    # Extended-stored-procedure / OS command
    ("xp_cmdshell", re.compile(
        r"\bxp_cmdshell\b", re.IGNORECASE,
    ), "xp_cmdshell (OS command execution)", 1.0),
    ("openrowset", re.compile(
        r"\bOPENROWSET\s*\(", re.IGNORECASE,
    ), "OPENROWSET (external data)", 0.9),
]


class SQLInjectionAnalyzer:
    """Analyzes LLM-generated SQL for injection artifacts.

    This is the **post-model** safety gate: even if the prompt-level
    scanner (AQD-001) passed the query, the generated SQL itself is
    inspected for dangerous constructs.
    """

    def analyze(self, raw_sql: str) -> InjectionAnalysisResult:
        """Analyze *raw_sql* for injection patterns.

        Parameters
        ----------
        raw_sql:
            The SQL statement produced by the LLM.

        Returns
        -------
        InjectionAnalysisResult
            Contains ``is_safe``, ``risk_score``, ``threats``,
            ``matched_rules``, and ``sanitized_sql``.
        """
        threats: list[str] = []
        matched_rules: list[str] = []
        max_score: float = 0.0

        for rule_name, pattern, threat_label, score in _RULES:
            if pattern.search(raw_sql):
                threats.append(threat_label)
                matched_rules.append(rule_name)
                if score > max_score:
                    max_score = score

        # Risk score: use the max individual score, boosted by the count
        # of distinct rule matches.
        if matched_rules:
            count_boost = min(0.3, (len(matched_rules) - 1) * 0.05)
            risk_score = min(1.0, max_score + count_boost)
        else:
            risk_score = 0.0

        is_safe = risk_score < 0.5

        # Sanitize: strip the most dangerous constructs
        sanitized = raw_sql
        for rule_name, pattern, _, sc in _RULES:
            if sc >= 0.9:
                sanitized = pattern.sub("/* [BLOCKED] */", sanitized)

        if not is_safe:
            logger.warning(
                "sql_injection_detected",
                risk_score=risk_score,
                threats=threats,
                sql_preview=raw_sql[:120],
            )

        return InjectionAnalysisResult(
            is_safe=is_safe,
            risk_score=round(risk_score, 4),
            threats=threats,
            matched_rules=matched_rules,
            sanitized_sql=sanitized,
        )
